// Code generated by BabelSuite. DO NOT EDIT.
"$schema": "https://schemas.babelsuite.dev/mock-exchange-source-v1.json"
suite: "electronics-lab"
artifact: "mock/spice-service/simulate.cue"
operationId: "spice-simulate"
adapter: "rest"
dispatcher: "apisix"
contractPath: "api/spice-service.yaml#/paths/~1simulate/post"
resolverUrl: "/internal/mock-data/electronics-lab/spice-service/spice-simulate"
runtimeUrl: "/mocks/rest/electronics-lab/spice-service/simulate"
examples: {
  "rc-sim": {
    dispatch: []
    requestSchema: {
      headers: {
        "content-type": "application/json"
      }
      body: {
        analysis:  "transient"
        probe_node: "2"
      }
    }
    responseSchema: {
      status: "200"
      mediaType: "application/json"
      body: {
        // RC filter rising to ~5V within 10ms — rise time ≈ 2.2ms, peak ≈ 5.0V
        // Both within plugin thresholds (max_rise_ms=3.0, max_voltage=5.5)
        times:    [0.0, 0.0005, 0.001, 0.0022, 0.003, 0.005, 0.007, 0.01]
        voltages: [0.0, 0.39,   0.78,  1.96,   3.16,  4.32,  4.75,  5.0]
        probe_node:   "2"
        trace_id:     string @gen(kind="uuid")
        simulated_at: string @gen(kind="timestamp")
      }
    }
  }
}
