// Code generated by BabelSuite. DO NOT EDIT.
"$schema": "https://schemas.babelsuite.dev/mock-exchange-source-v1.json"
suite: "electronics-lab"
artifact: "mock/verilog-service/simulate.cue"
operationId: "verilog-simulate"
adapter: "rest"
dispatcher: "apisix"
contractPath: "api/verilog-service.yaml#/paths/~1simulate/post"
resolverUrl: "/internal/mock-data/electronics-lab/verilog-service/verilog-simulate"
runtimeUrl: "/mocks/rest/electronics-lab/verilog-service/simulate"
examples: {
  "counter-sim": {
    dispatch: []
    requestSchema: {
      headers: {
        "content-type": "application/json"
      }
      body: {
        top_module: "tb_counter"
      }
    }
    responseSchema: {
      status: "200"
      mediaType: "application/json"
      body: {
        // Clean simulation: no compile errors, no sim errors, no X-state signals
        compile_errors: []
        sim_errors:     0
        x_signals:      []
        stdout:         "Time=0 | Reset=1 | Counter Output=0\nTime=10 | Reset=0 | Counter Output=0\nTime=20 | Reset=0 | Counter Output=1\nTime=30 | Reset=0 | Counter Output=2"
        trace_id:       string @gen(kind="uuid")
        simulated_at:   string @gen(kind="timestamp")
      }
    }
  }
}
