{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babelsuite.fullname" . }}
  labels:
    {{- include "babelsuite.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
  {{- if .Values.secrets.adminEmail }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  {{- end }}
  {{- if .Values.secrets.adminPassword }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.agentSharedSecret }}
  AGENT_SHARED_SECRET: {{ .Values.secrets.agentSharedSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.mockSharedSecret }}
  MOCK_SHARED_SECRET: {{ .Values.secrets.mockSharedSecret | quote }}
  {{- end }}
{{- end }}
