// Code generated by BabelSuite. DO NOT EDIT.
"$schema": "https://schemas.babelsuite.dev/mock-exchange-source-v1.json"
suite: "electronics-lab"
artifact: "mock/control-service/simulate.cue"
operationId: "control-simulate"
adapter: "rest"
dispatcher: "apisix"
contractPath: "api/control-service.yaml#/paths/~1simulate/post"
resolverUrl: "/internal/mock-data/electronics-lab/control-service/control-simulate"
runtimeUrl: "/mocks/rest/electronics-lab/control-service/simulate"
examples: {
  "mass-spring-sim": {
    dispatch: []
    requestSchema: {
      headers: {
        "content-type": "application/json"
      }
      body: {
        analysis: "step"
      }
    }
    responseSchema: {
      status: "200"
      mediaType: "application/json"
      body: {
        // Critically damped G(s)=1/(s²+2s+1): stable, settling≈4s, 0% overshoot, dc_gain=1.0
        // All within thresholds: max_settling_time=8.0, max_overshoot_pct=5.0, dc_gain ∈ [0.9,1.1]
        stable:        true
        settling_time: 4.1
        overshoot_pct: 0.0
        dc_gain:       1.0
        trace_id:      string @gen(kind="uuid")
        simulated_at:  string @gen(kind="timestamp")
      }
    }
  }
}
